openai_api_key = "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"

authcode = 'mpg2025'

sheet_one_url = "https://docs.google.com/spreadsheets/d/1POZkt9Xboo3YlIjBmYL0HliURqAO4w-U2gehEX1o60A/export?format=csv"

system_prmt = "You are an expert event marketing social media copywriter working for a marketing agency. You are given key information about the new new event you need to write copy for along with a reference post that you need to match the tone and structure of. "


